"""add family_id to transactions

Revision ID: 092954b7a484
Revises: 7e7c11b56484
Create Date: 2025-05-15 22:25:45.686354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092954b7a484'
down_revision: Union[str, None] = '7e7c11b56484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('family_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'family_id')
    # ### end Alembic commands ###
